# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c094cabee4f59f186276b1261d85445bbd2596ee7cd6d8074cec7418bdac1f718cb2237efa7ea35041e546fdf6f0f2141c763f637f7a5e1644eeb4a8338e760d

test:
  secret_key_base: 832ddbfe94a874d6f7d763f66903fe6abcdff2d1f39852e08c76121da8a06a3d9d2b36b4e999138b80da71e11a8a9ff1c07c6dd5071088cd53a698d12bf8894c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
